### ISSUE TITLE
Players can't vote anymore.

### ISSUE THREAD

**Issue by Arctiblaine** [ProjectInfinity/PocketVote-Nukkit#2]
![what-is-this](https://cloud.githubusercontent.com/assets/12755193/26090563/a994141c-39ba-11e7-81f9-f8eeccc3ec01.JPG)

This is what happens when players vote.

**Comment by ProjectInfinity** [comment]
Thanks. Will investigate.

**Comment by ProjectInfinity** [comment]
Fixed in https://github.com/ProjectInfinity/PocketVote-Nukkit/commit/4f906381d648a9f5a0bcc7e86db46cdf665a6024
