### ISSUE TITLE
Votes not being received

### ISSUE THREAD

**Issue by imjack** [ProjectInfinity/PocketVote-Nukkit#3]
Hello, 

I've recently changed hosts and I ain't seeming to receiving votes from websites. I can't understand why this is happening. The identifier and the secret key is correct however I just don't seem to get them. Is there a certain port I should have open to get them?

Thanks jack.

**Comment by ProjectInfinity** [comment]
No ports are required to be opened.
If you have double checked that your identity and secret is IDENTICAL in config.yml as well as on the voting sites, please try running a MTR **FROM YOUR SERVER** to https://api.pocketvote.io

Here's how to do it:
`mtr -s 1000 -r -c 1000 api.pocketvote.io`
It will take about 15 minutes to complete.

Then post the results in a pastebin.

**Comment by ProjectInfinity** [comment]
I also highly encourage you to try the PocketMine plugin to see if you have the issue there as well, the config is almost identical. Doing so would rule out the possibility of an issue on my end.

I am currently working on a diagnosis feature for the PocketMine plugin considering over 95% of my userbase is PocketMine based. This functionality will make it to Nukkit _eventually_ along with APIv2.

![Screenshot](https://i.imgur.com/Ta74ytV.png)

**Comment by ProjectInfinity** [comment]
I have confirmed that PocketVote does not seem to be receiving votes from https://minecraftpocket-servers.com/

I have notified the owner and hope that it is resolved quickly.

**Comment by ProjectInfinity** [comment]
Issue has been fixed. :)

**Comment by imjack** [comment]
I'll look into it if Its fixed my issue. I'm just busy at the moment
