### ISSUE TITLE
Where's the .jar

### ISSUE THREAD

**Issue by UnexMC** [ProjectInfinity/PocketVote-Nukkit#4]
Could you please release the jar of this plugin??

**Comment by DaMatrix** [comment]
You could use [my Jenkins](http://jenkins.daporkchop.net/job/Plugins/job/PocketVote-Nukkit/lastSuccessfulBuild/artifact/target/) if you like, otherwise just use `msv package` in the root directory and copy the jar from `target/`

**Comment by ProjectInfinity** [comment]
PocketVote.io
